apiVersion: v1
kind: Secret
metadata:
  name: backend-tbc-ontap-secret
type: Opaque
stringData:
  username: admin
  password: password
---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-ontap-nas-new
spec:
  version: 1
  storageDriverName: ontap-nas
  managementLIF: 10.xx.xx.xx
  dataLIF: 10.xx.xx.xx
  backendName: tbc-ontap-nas
  svm: svm
  exportPolicy: default
  credentials:
    name: backend-tbc-ontap-secret

