prefix = "fabianb-"
gcp-project = "csa-emea-pool-user-05"
gcp-sa = "fulladmin@csa-emea-pool-user-05.iam.gserviceaccount.com"

region = "europe-west3"
network = "default"
subnetwork = ""
ip_range_pods = ""
ip_range_services = ""
nodepoolname = "tf-gen-node-pool"
